import json

coco_classes = [
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush"
]

obj365_classes = [
    "Person",
    "Sneakers",
    "Chair",
    "Other Shoes",
    "Hat",
    "Car",
    "Lamp",
    "Glasses",
    "Bottle",
    "Desk",
    "Cup",
    "Street Lights",
    "Cabinet/shelf",
    "Handbag/Satchel",
    "Bracelet",
    "Plate",
    "Picture/Frame",
    "Helmet",
    "Book",
    "Gloves",
    "Storage box",
    "Boat",
    "Leather Shoes",
    "Flower",
    "Bench",
    "Potted Plant",
    "Bowl/Basin",
    "Flag",
    "Pillow",
    "Boots",
    "Vase",
    "Microphone",
    "Necklace",
    "Ring",
    "SUV",
    "Wine Glass",
    "Belt",
    "Moniter/TV",
    "Backpack",
    "Umbrella",
    "Traffic Light",
    "Speaker",
    "Watch",
    "Tie",
    "Trash bin Can",
    "Slippers",
    "Bicycle",
    "Stool",
    "Barrel/bucket",
    "Van",
    "Couch",
    "Sandals",
    "Bakset",
    "Drum",
    "Pen/Pencil",
    "Bus",
    "Wild Bird",
    "High Heels",
    "Motorcycle",
    "Guitar",
    "Carpet",
    "Cell Phone",
    "Bread",
    "Camera",
    "Canned",
    "Truck",
    "Traffic cone",
    "Cymbal",
    "Lifesaver",
    "Towel",
    "Stuffed Toy",
    "Candle",
    "Sailboat",
    "Laptop",
    "Awning",
    "Bed",
    "Faucet",
    "Tent",
    "Horse",
    "Mirror",
    "Power outlet",
    "Sink",
    "Apple",
    "Air Conditioner",
    "Knife",
    "Hockey Stick",
    "Paddle",
    "Pickup Truck",
    "Fork",
    "Traffic Sign",
    "Ballon",
    "Tripod",
    "Dog",
    "Spoon",
    "Clock",
    "Pot",
    "Cow",
    "Cake",
    "Dinning Table",
    "Sheep",
    "Hanger",
    "Blackboard/Whiteboard",
    "Napkin",
    "Other Fish",
    "Orange/Tangerine",
    "Toiletry",
    "Keyboard",
    "Tomato",
    "Lantern",
    "Machinery Vehicle",
    "Fan",
    "Green Vegetables",
    "Banana",
    "Baseball Glove",
    "Airplane",
    "Mouse",
    "Train",
    "Pumpkin",
    "Soccer",
    "Skiboard",
    "Luggage",
    "Nightstand",
    "Tea pot",
    "Telephone",
    "Trolley",
    "Head Phone",
    "Sports Car",
    "Stop Sign",
    "Dessert",
    "Scooter",
    "Stroller",
    "Crane",
    "Remote",
    "Refrigerator",
    "Oven",
    "Lemon",
    "Duck",
    "Baseball Bat",
    "Surveillance Camera",
    "Cat",
    "Jug",
    "Broccoli",
    "Piano",
    "Pizza",
    "Elephant",
    "Skateboard",
    "Surfboard",
    "Gun",
    "Skating and Skiing shoes",
    "Gas stove",
    "Donut",
    "Bow Tie",
    "Carrot",
    "Toilet",
    "Kite",
    "Strawberry",
    "Other Balls",
    "Shovel",
    "Pepper",
    "Computer Box",
    "Toilet Paper",
    "Cleaning Products",
    "Chopsticks",
    "Microwave",
    "Pigeon",
    "Baseball",
    "Cutting/chopping Board",
    "Coffee Table",
    "Side Table",
    "Scissors",
    "Marker",
    "Pie",
    "Ladder",
    "Snowboard",
    "Cookies",
    "Radiator",
    "Fire Hydrant",
    "Basketball",
    "Zebra",
    "Grape",
    "Giraffe",
    "Potato",
    "Sausage",
    "Tricycle",
    "Violin",
    "Egg",
    "Fire Extinguisher",
    "Candy",
    "Fire Truck",
    "Billards",
    "Converter",
    "Bathtub",
    "Wheelchair",
    "Golf Club",
    "Briefcase",
    "Cucumber",
    "Cigar/Cigarette ",
    "Paint Brush",
    "Pear",
    "Heavy Truck",
    "Hamburger",
    "Extractor",
    "Extention Cord",
    "Tong",
    "Tennis Racket",
    "Folder",
    "American Football",
    "earphone",
    "Mask",
    "Kettle",
    "Tennis",
    "Ship",
    "Swing",
    "Coffee Machine",
    "Slide",
    "Carriage",
    "Onion",
    "Green beans",
    "Projector",
    "Frisbee",
    "Washing Machine/Drying Machine",
    "Chicken",
    "Printer",
    "Watermelon",
    "Saxophone",
    "Tissue",
    "Toothbrush",
    "Ice cream",
    "Hotair ballon",
    "Cello",
    "French Fries",
    "Scale",
    "Trophy",
    "Cabbage",
    "Hot dog",
    "Blender",
    "Peach",
    "Rice",
    "Wallet/Purse",
    "Volleyball",
    "Deer",
    "Goose",
    "Tape",
    "Tablet",
    "Cosmetics",
    "Trumpet",
    "Pineapple",
    "Golf Ball",
    "Ambulance",
    "Parking meter",
    "Mango",
    "Key",
    "Hurdle",
    "Fishing Rod",
    "Medal",
    "Flute",
    "Brush",
    "Penguin",
    "Megaphone",
    "Corn",
    "Lettuce",
    "Garlic",
    "Swan",
    "Helicopter",
    "Green Onion",
    "Sandwich",
    "Nuts",
    "Speed Limit Sign",
    "Induction Cooker",
    "Broom",
    "Trombone",
    "Plum",
    "Rickshaw",
    "Goldfish",
    "Kiwi fruit",
    "Router/modem",
    "Poker Card",
    "Toaster",
    "Shrimp",
    "Sushi",
    "Cheese",
    "Notepaper",
    "Cherry",
    "Pliers",
    "CD",
    "Pasta",
    "Hammer",
    "Cue",
    "Avocado",
    "Hamimelon",
    "Flask",
    "Mushroon",
    "Screwdriver",
    "Soap",
    "Recorder",
    "Bear",
    "Eggplant",
    "Board Eraser",
    "Coconut",
    "Tape Measur/ Ruler",
    "Pig",
    "Showerhead",
    "Globe",
    "Chips",
    "Steak",
    "Crosswalk Sign",
    "Stapler",
    "Campel",
    "Formula 1 ",
    "Pomegranate",
    "Dishwasher",
    "Crab",
    "Hoverboard",
    "Meat ball",
    "Rice Cooker",
    "Tuba",
    "Calculator",
    "Papaya",
    "Antelope",
    "Parrot",
    "Seal",
    "Buttefly",
    "Dumbbell",
    "Donkey",
    "Lion",
    "Urinal",
    "Dolphin",
    "Electric Drill",
    "Hair Dryer",
    "Egg tart",
    "Jellyfish",
    "Treadmill",
    "Lighter",
    "Grapefruit",
    "Game board",
    "Mop",
    "Radish",
    "Baozi",
    "Target",
    "French",
    "Spring Rolls",
    "Monkey",
    "Rabbit",
    "Pencil Case",
    "Yak",
    "Red Cabbage",
    "Binoculars",
    "Asparagus",
    "Barbell",
    "Scallop",
    "Noddles",
    "Comb",
    "Dumpling",
    "Oyster",
    "Table Teniis paddle",
    "Cosmetics Brush/Eyeliner Pencil",
    "Chainsaw",
    "Eraser",
    "Lobster",
    "Durian",
    "Okra",
    "Lipstick",
    "Cosmetics Mirror",
    "Curling",
    "Table Tennis ",
]

dst2src = {
    "shoes": {"sneakers", "other shoes", "leather shoes", "boots", "slippers", "sandals", "high heels",
              "skating and skiing shoes", "arctic_(type_of_shoe)", "boot", "flip-flop_(sandal)",
              "sandal_(type_of_shoe)", "shoe", "ski_boot", "high_heels", "leather_shoes", "roller_skate",
              "slipper_(footwear)"},
    "hat": {"hat", "helmet", "baseball_cap", "beanie", "bottle_cap", "cap_(headwear)", "cowboy_hat", "cap", "crown",
            "football_helmet", "skullcap", "sombrero", "sunhat", "swim_cap"},
    "lamp": {"lamp", "lantern", "chandelier", "headlight", "lightbulb", "reflector", "brake_light", "taillight",
             "spotlight", "flashlight"},
    "cabinet": {"cabinet", "shelf", "nightstand", "armoire", "drawer", "bookcase", "file_cabinet", "fume_hood",
                "spice_rack", "wardrobe", "wine_rack"},
    "box": {"pencil case",  "storage box", "computer box", "crate", "cooler", "cooler_(for_food)", "luggage",
            "briefcase", "trunk", "computer_box", "pencil_box"},
    "bag": {"handbag", "satchel", "tote_bag", "duffel_bag", "plastic_bag", "wristlet", "shopping_bag", "shoulder_bag",
            "clutch_bag", "punching_bag"},
    "picture": {"picture", "frame", "painting"},
    "gloves": {"gloves", "baseball glove", "baseball_glove", "glove"},
    "flower": {"flower", "flower_arrangement", "sunflower", "lavender", "lily", "rose"},
    "plant": {"plant", "potted plant", "bamboo", "christmas_tree", "maple", "palm_tree", "potted_plant", "tree",
              "willow"},
    "table": {"dinning table", "desk", "coffee table", "side table", "billards", "dining_table", "kitchen_table",
              "pool_table"},
    "chair": {"bench", "stool", "wheelchair", "armchair", "deck_chair", "folding_chair", "couch", "sofa",
              "training_bench"},
    "bowl": {"bowl", "basin"},
    "glasses": {"spectacles", "binoculars", "goggles", "sunglasses"},
    "bottle": {"vase", "tea pot", "jug", "kettle", "teakettle",  "flask", "pot", "beer_bottle", "dispenser", "jar",
               "flowerpot", "water_bottle", "wine_bottle", "shampoo", "pitcher_(vessel_for_liquid)", "cleansing_agent",
               "perfume", "shaker", "shaving_cream", "teapot", "thermos_bottle", "water_jug"},
    "drink": {"alcohol", "cocktail", "fruit_juice", "milk"},
    "oil": {"olive_oil"},
    "can": {"canned",  "aerosol_can",  "beer_can", "saltshaker", "pop_(soda)", },

    "cup": {"wine glass", "glass_(drink_container)", "mug", "wineglass", "dixie_cup", "measuring_cup"},
    "monitor": {"tv", "monitor", "television_set", "monitor_(computer_equipment) computer_monitor", "computer_monitor",
                "tablet_computer"},
    "jewelry": {"necklace", "ring", "bracelet", "anklet", "bead", "choker", "earring"},
    "speaker": {"speaker", "bullhorn", "megaphone", "amplifier", "speaker_(stero_equipment)"},
    "bucket": {"trash bin can", "barrel", "bakset", "basket", "trash_can"},


    # vehicle
    "truck": {"pickup truck",  "fire truck", "heavy truck", "pickup_truck", "fire_engine", "snowplow", "trailer_truck"},

    "machinery vehicle": {"machinery vehicle", "bulldozer", "crane"},
    "car": {"suv", "sports car", "formula 1", "cab_(taxi)", "car_(automobile)", "limousine", "race_car", "taxi"},
    "army_tank": {"army_tank"},
    "motorcycle": {"motor_scooter", "scooter", "hoverboard", "segway", "snowmobile", "water_scooter"},
    "carriage": {"carriage", "cart", "golfcart", "horse_carriage"},
    "cycle": {"bike", "bicycle", "tricycle", "stationary_bicycle", "unicycle"},
    "train": {"railcar_(part_of_a_train)", "train_(railroad_vehicle)", "passenger_car_(part_of_a_train)"},
    "bus": {"ambulance", "van", "bus_(vehicle)", "minivan"},

    "mat": {"carpet", "bath_mat", "place_mat",  "tablecloth", "tarp", "runner_(carpet)"},
    "toy": {"stuffed toy", "figurine", "teddy_bear", "doll", "lego"},
    "boat": {"sailboat", "oar", "canoe", "gondola_(boat)"},
    "tent": {"tent", "faucet", "awning"},
    "wall socket": {"power outlet", "wall_socket"},
    "air conditioner": {"air conditioner", "air_conditioner"},
    "traffic sign": {"traffic sign", "stop sign", "speed limit sign", "crosswalk sign", "stop_sign", "street_sign",
                     "traffic light", "traffic_light", "parking_meter"},
    "traffic cone": {"traffic cone", "cone"},
    "balloon": {"ballon", "hotair ballon", "hot-air_balloon"},
    "hanger": {"hanger", "coat_hanger"},
    "fish": {"other fish", "goldfish", "dolphin", "rays_and_skates", "shark", "whale"},
    "toiletry": {"toiletry", "cosmetics"},
    "ball": {"soccer", "other balls", "baseball", "basketball", "american football", "tennis", "golf ball",
             "volleyball", "curling", "table tennis", "soccer_ball", "tennis_ball", "bowling_ball",
             "football_(american)", "golf_ball", "ping-pong_ball"},
    "board": {"skiboard", "snowboard", "skateboard", "surfboard", "cutting/chopping board", "chopping board",
              "blackboard/whiteboard", "blackboard", "whiteboard", "game board", "basketball_backboard",
              "chopping_board", "cupboard", "headboard", "signboard", "ski", "dartboard", "gameboard", "scoreboard"},
    "trolley": {"trolley", "baby_buggy", "stroller", "rickshaw", "handcart"},
    "earphone": {"head phone", "headset"},
    "other_foods": {"dessert", "ice cream",  "cheese", "string_cheese", "chips", "egg tart",
                    "butter", "crisp_(potato_chip)", "spring rolls", "dumpling", "pie", "bean_curd", "rice",  "sushi",
                    "burrito", "egg_roll", "egg_tart", "icecream", "popcorn", "taco"},
    "fries": {"french_fries", "french fries", },
    "candy": {"candy", "candy_bar"},
    "cake": {"cupcake", "cake", "birthday_cake", "pancake"},
    "cracker": {"cookies", "cookie", "muffin", "waffle"},
    "nuts": {"almond", "nuts", "nut"},

    "camera": {"surveillance camera", "surveillance"},
    "kitchen_tools": {"gas stove", "oven", "microwave", "microwave_oven", "stove", "coffee machine", "induction cooker",
               "toaster", "rice cooker", "blender", "pan_(for_cooking)", "frying_pan", "coffee_maker", "cooking_utensil",
               "grill", "eggbeater", "food_processor", "heater", "mixer_(kitchen_tool)", "cooker", "waffle_iron"},
    "tie": {"bow tie", "bow_(decorative_ribbons)", "bow-tie", "necktie"},
    "paper": {"toilet paper", "tissue", "toilet tissue", "napkin", "notepaper","newspaper",
              "paper_towel", "tissue_paper", "toilet_tissue", "tinfoil", "diaper"},
    "card": {"poker_card",  "poker card", "card", },
    "chopsticks": {"chopsticks", "chopstick"},
    "fire hydrant": {"fire extinguisher", "fireplug", "fire_extinguisher"},
    "pen": {"marker", "pencil", "eyeliner pencil", "lipstick"},

    "converter": {"converter"},
    "cigarette": {"cigar", "cigarette"},
    "brush": {"paint brush", "toothbrush", "broom", "mop", "comb", "cosmetics brush", "hairbrush", "paintbrush",
              "scrubbing_brush"},
    "extractor": {"extractor"},
    "cord": {"extention cord", "thread"},
    "folder": {"folder", "binder"},
    "ball_bat": {"golf club", "baseball bat", "hockey stick", "cue", "tennis racket", "racket", "table teniis paddle",
                 "table tennis paddle", "baseball_bat", "coffee_table", "tennis_racket", "golf_club", "hockey_stick",
                 "table_tennis_racket"},
    "balance_beam": {"balance_beam"},
    "ship": {"ship", "barge", "cargo_ship"},
    "submarine": {"submarine"},
    "swing": {"swing"},

    "beans": {"green beans", "green_bean", "pea_(food)", "legume"},
    "washing machine": {"drying machine", "cleaning products", "dishwasher", "automatic_washer", "vacuum_cleaner"},

    "scale": {"scale", "scale_(measuring_instrument)"},
    "trophy": {"trophy", "trophy_cup"},
    "tape": {"tape",  "tape_(sticky_cloth_or_paper)", "band_aid"},
    "tablet": {"tablet"},
    "hurdle": {"hurdle"},
    "horizontal_bar": {"horizontal_bar"},
    "fishing rod": {"fishing rod", "fishing_rod"},
    "stick": {"measuring_stick", "stick"},
    "medal": {"medal", "award"},
    "swan": {"swan"},
    "musical instrument": {"trombone", "cello", "piano", "flute", "violin", "guitar", "cymbal", "drum", "saxophone",
                           "bass_horn", "tuba", "trumpet", "bagpipe", "accordion", "banjo", "clarinet",
                           "drum_(musical_instrument)", "harmonica", "harmonium", "harp", "musical_instrument"},
    "bell": {"wind_chime", "bell"},
    "sink": {"bathtub", "urinal", "aquarium", "cistern", "kitchen_sink", "tank_(storage_vessel)"},



    "other vegetables": {"eggplant", "garlic", "mushroon", "mushroom", "cabbage", "red cabbage", "asparagus", "radish",
                         "okra", "pumpkin", "pepper", "cucumber", "green vegetables", "broccoli", "cabbage", "lettuce",
                         "artichoke", "bell_pepper", "brussels_sprouts", "cauliflower", "celery", "pickle", "zucchini",
                         "chili_(vegetable)", "vegetables"},
    "onion": {"onion",  "green onion", "green_onion"},
    "other fruits": {"plum", "kiwi fruit", "kiwi_fruit",  "avocado", "cherry", "coconut",  "pomegranate",
                     "papaya", "grapefruit",  "durian",  "mango", "grape", "pear", "peach",
                     "pineapple", "apricot", "fig_(fruit)", "fruit"},
    "berry": {"raspberry", "blackberry", "blueberry", "strawberry", },
    "melon": {"cantaloup", "hamimelon", "watermelon"},
    "orange": {"lime", "orange_(fruit)", "mandarin_orange", "lemon",},
    "tomato": {"tomato", },
    "potato": {"potato",},
    "corn": {"corn", "edible_corn",},




    "router": {"modem", "router_(computer_equipment)"},
    "cd": {"cd"},
    "noodles": {"pasta", "noddles"},
    "bread": {"hot dog", "hamburger", "doughnut", "donut", "sandwich", "toast", "baozi", "bagel", "baguet", "bun",
              "crumb", "pastry", "hot_dog", "pretzel"},
    "microphone": {"recorder"},
    "eraser": {"board eraser", "board_eraser"},
    "ruler": {"measur", "tape measur"},
    "pig": {"hog"},
    "showerhead": {"showerhead", "shower_head"},
    "shrimp": {"prawn", "lobster"},
    "meat": {"steak", "meat ball",  "sausage", "beef", "beef_(food)", "ham", "meatball", "steak_(food)"},
    "stapler": {"stapler", "stapler_(stapling_machine)"},
    "campel": {"campel"},


    "butterfly": {"buttefly"},

    "hair_dryer": {"hair dryer", "hair_dryer"},
    "hand_dryer": {"hand_dryer"},
    "jellyfish": {"jellyfish"},
    "treadmill": {"treadmill"},
    "frisbee": {"target"},
    "lighter": {"igniter"},
    "french": {"french"},
    "yak": {"yak"},
    "shellfish": {"scallop", "oyster", "seashell"},
    "dumbbell": {"barbell"},
    "mirror": {"cosmetics mirror", "rearview_mirror"},
    "airplane": {"airplane", "plane", "helicopter", "space_shuttle"},
    "lifesaver": {"lifesaver", "life_buoy", "life_jacket"},
    "clothes": {"shirt", "apron", "armor", "blazer", "blouse", "coat",  "jacket",
                "jersey", "polo_shirt", "ski_parka", "sweater", "sweatshirt", "swimsuit", "tank_top_(clothing)", "vest",
                "wet_suit", "suit_(clothing)", "dress_suit", "raincoat", "scarf", "headscarf", "dress", "brassiere",
                "sportswear"},
    "pants": {"short_pants", "jean", "trousers"},
    "skirts": {"skirt", "ballet_skirt"},
    "plate": {"plate", "dish", "paper_plate", "saucer", "tray", "ashtray"},
    "flag": {"flag", "parasail_(sports)"},
    "pillow": {"pillow"},
    "belt": {"belt", "armband", "dog_collar", "headband", "lanyard", "rubber_band", "strap", "seat_belt"},
    "watch": {"watch"},
    "clock": {"alarm_clock", "clock", "digital_clock"},
    "towel": {"towel", "bath_towel", "hand_towel"},
    "blanket": {"saddle_blanket", "quilt", "mattress"},
    "candle": {"candle"},
    "paddle": {"paddle"},
    "tripod": {"tripod"},
    "fan": {"fan", "propeller", "vent"},
    "telephone": {"telephone"},
    "duck": {"duck"},

    "ladder": {"ladder"},
    "radiator": {"radiator"},

    "egg": {"egg"},
    "mask": {"mask", "visor", "blinker",  "lampshade"},
    "curtain": {"curtain", "shower_curtain", "window_blind"},
    "slide": {"slide"},
    "projector": {"projector"},
    "printer": {"printer"},
    "wallet": {"purse"},
    "deer": {"deer"},
    "goose": {"goose"},

    "key": {"key"},
    "penguin": {"penguin"},

    "soap": {"soap"},
    "globe": {"globe"},
    "calculator": {"calculator"},

    "antenna": {"antenna"},
    "sauce": {"applesauce", "guacamole", "salad"},
    "atomizer": {"atomizer"},
    "bait": {"bait"},
    "banner": {"banner", "billboard", "poster"},
    "pad": {"baseball_base", "coaster", "cushion", "home_plate_(baseball)", "knee_pad",
            "mousepad", "notepad"},
    "saddle": {"saddle_(on_an_animal)"},
    "belt_buckle": {"belt_buckle"},
    "bolt": {"bolt", "deadbolt", "doorknob", "knob", "latch"},
    "book": {"booklet", "magazine"},
    "bull": {"bull", "calf", "cow"},
    "buoy": {"buoy"},
    "button": {"button"},
    "holder": {"candle_holder", "cake_stand"},
    "cell phone": {"cellular_telephone"},
    "clock_tower": {"clock_tower"},
    "coin": {"coin"},
    "keyboard": {"computer_keyboard"},
    "condiment": {"condiment"},
    "control": {"remote", "remote_control"},
    "crossbar": {"crossbar"},
    "fireplace": {"fireplace"},

    "gravestone": {"gravestone"},
    "handle": {"handle"},
    "hinge": {"hinge"},
    "hook": {"hook"},
    "pipe": {"hose", "garden_hose", "fire_hose", "straw_(for_drinking)"},
    "laptop": {"laptop_computer"},
    "license plate": {"license_plate"},
    "log": {"log"},
    "magnet": {"magnet"},
    "post": {"mast",  "lamppost", "street lights", "pole", "ski_pole", "streetlight", "telephone_pole", "flagpole"},
    "motor": {"motor"},
    "computer_mouse": {"mouse_(computer_equipment)"},
    "sail": {"sail"},
    "sock": {"sock"},
    "statue": {"statue_(sculpture)", "sculpture"},
    "steering wheel": {"steering_wheel"},
    "stirrup": {"stirrup"},
    "tag": {"tag"},
    "towel_rack": {"towel_rack"},
    "wheel": {"wheel"},
    "windshield wiper": {"windshield_wiper"},
    "refrigerator": {"refrigerator"},
    "manhole": {"manhole"},
    "toothpick": {"toothpick"},
    "clip": {"clip"},
    "cork_(bottle_plug)": {"cork_(bottle_plug)"},
    "heart": {"heart"},
    "parasail": {"parasail_(sports)"},
    "toothpaste": {"toothpaste"},
    "cover": {"cover"},


    # animals
    "alpaca": {"alpaca"},
    "armadillo": {"armadillo"},
    "bat": {"bat_(animal)"},
    "camel": {"camel"},
    "bird": {"wild bird", "pigeon", "parrot", "gull", "flamingo", "canary", "crow", "eagle", "owl", "sparrow"},
    "dinosaur": {"dinosaur"},
    "ferret": {"ferret"},
    "fox": {"fox"},
    "frog": {"frog"},
    "crab": {"crab", "crab_(animal)"},
    "antelope": {"antelope", "gazelle"},
    "panda": {"giant_panda"},
    "red_panda": {"red_panda"},
    "lion": {"lion"},
    "monkey": {"monkey", "baboon", "gorilla"},
    "rabbit": {"rabbit"},
    "alligator": {"crocodile"},
    "mouse": {"hamster", "mouse", "rat"},
    "seal": {"seal", "harbor_seal"},
    "hedgehog": {"hedgehog"},
    "hippopotamus": {"hippopotamus"},
    "goat": {"goat", "sheep", "lamb_(animal)"},
    "jaguar": {"jaguar"},
    "kangaroo": {"kangaroo"},
    "chicken": {"chicken", "chicken_(animal)", "turkey"},
    "koala": {"koala"},
    "other_animal": {"isopod"},
    "lizard": {"lizard"},
    "lynx": {"lynx"},
    "donkey": {"domestic_ass", "mule"},
    "ostrich": {"ostrich"},
    "otter": {"otter"},
    "polar_bear": {"polar_bear"},
    "porcupine": {"porcupine"},
    "raccoon": {"raccoon"},
    "rhinoceros": {"rhinoceros"},
    "seahorse": {"seahorse"},
    "skunk": {"skunk"},
    "snake": {"snake"},
    "squid": {"squid_(food)"},
    "squirrel": {"squirrel"},
    "starfish": {"starfish"},
    "tiger": {"tiger"},
    "turtle": {"turtle"},
    "wolf": {"wolf"},

    # insects
    "ant": {"ant"},
    "bee": {"bee"},
    "beehive": {"beehive"},
    "worm": {"caterpillar", "centipede"},
    "dragonfly": {"dragonfly"},
    "ladybug": {"ladybug"},
    "other_insect": {"insect"},
    "scorpion": {"scorpion"},
    "snail": {"snail"},
    "spider": {'spider'},

    # tools
    "opener": {"bottle_opener", "can_opener"},
    "drill": {"chisel", "drill", "electric drill"},
    "grinder": {"grinder"},
    "saw": {"handsaw", "chainsaw"},
    "spoon": {"spoon", "ladle"},
    "other_tools": {"pliers", "hammer", "screwdriver", "ax", "spatula", "shovel", },
    "nail": {"nail"},
    "pencil_sharpener": {"pencil_sharpener"},
    "tong": {"tongs", "tong"},
    "wrench": {"wrench"},

    # weapons
    "bow": {"bow_(weapon)"},
    "cannon": {"cannon"},
    "knife": {"dagger", "knife"},
    "missile": {"missile"},
    "gun": {"gun", "pistol"},
    "pizza_cutter": {"pizza_cutter"},
    "sword": {"sword"},


    # furniture
    "bed": {"dog_bed", "infant_bed", "sofa_bed"},
    "cat_furniture": {"cat_furniture"},
    "door": {"door", "porch"},
    "window": {"window"},

    # building
    "other_building": {"building", "castle", "house", "lighthouse", "tower", "tree_house", "windmill"},
    "ferris_wheel": {"ferris_wheel"},
    "spring": {"fountain", "spring"},
    "pool": {"swimming_pool"},

    "cassette_deck": {"cassette_deck"},
    "crutch": {"crutch"},
    "dice": {"dice"},
    "envelope": {"envelope"},
    "fax": {"fax"},
    "humidifier": {"humidifier"},
    "ipod": {"ipod"},
    "indoor_rower": {"indoor_rower"},
    "iron": {"iron_(for_clothing)"},
    "switch": {"light_switch"},
    "parachute": {"parachute"},
    "radio": {"radio_receiver", "radio"},
    "sewing_machine": {"sewing_machine"},
    "snowman": {"snowman"},
    "stethoscope": {"stethoscope"},
    "stretcher": {"stretcher"},
    "injector": {"syringe", "injector"},
    "typewriter": {"typewriter"}
}

ignored_class = set()

for r_src_classes in dst2src.values():
    for r_src_class in r_src_classes:
        if r_src_class.lower() not in dst2src.keys():
            ignored_class.add(r_src_class.lower())

for r_coco_class in coco_classes:

    if r_coco_class.lower() in ignored_class:
        continue

    if r_coco_class.lower() not in dst2src:
        dst2src[r_coco_class.lower()] = set()
    dst2src[r_coco_class.lower()].add(r_coco_class.lower())

with open("D:/数据集/Coco2017/lvis_v1_train_categories.json", "r") as lvis_classes_file:
    lvis_class_infos = json.load(lvis_classes_file)

lvis_classes = []

for r_class in lvis_class_infos:
    r_class_name = r_class.get("name", None)
    r_num_instance = r_class.get("instance_count", 0)
    if r_class_name.lower() in ignored_class:
        continue

    if r_num_instance < 300:
        continue
    lvis_classes.append(r_class_name)
    # r_class_synonyms = r_class.get("synonyms", [])

    # if r_class_name.lower() not in dst2src:
    #     dst2src[r_class_name.lower()] = set()

    # for r_synonyms in r_class_synonyms:
        # if r_synonyms == "television_set":
        #     continue
        # dst2src[r_class_name.lower()].add(r_synonyms.lower())

src2dst = {}

for r_dst_class, r_obj_classes in dst2src.items():
    src2dst[r_dst_class.lower()] = r_dst_class.lower()
    for r_obj_class in r_obj_classes:
        src2dst[r_obj_class.lower()] = r_dst_class.lower()

#
# for i_class, r_obj_class in enumerate(obj365_classes):
#     r_dst_class = None
#     for r_seg in r_obj_class.split("/"):
#         r_seg = r_seg.strip(" ")
#         r_dst_class = src2dst.get(r_seg.lower(), None)
#         if isinstance(r_dst_class, str) is True:
#             break
#
#     if isinstance(r_dst_class, str) is False:
#         raise Exception(f"unresolved class: {r_obj_class.lower() }")
#     print(f"[{i_class}]: {r_obj_class} => {r_dst_class}")
#
#
# for i_class, r_lvis_class in enumerate(lvis_classes):
#
#     r_dst_class = None
#     for r_seg in r_lvis_class.split("/"):
#         r_seg = r_seg.strip(" ")
#         r_dst_class = src2dst.get(r_seg.lower(), None)
#         if isinstance(r_dst_class, str) is True:
#             break
#
#     if isinstance(r_dst_class, str) is False:
#         raise Exception(f"unresolved class: {r_lvis_class.lower() }")
#     print(f"[{i_class}]: {r_lvis_class} => {r_dst_class}")


with open("bigdetection_synsets.txt", "r") as bigdet_class_file:
    for i_class, r_src_class in enumerate(bigdet_class_file.readlines()):
        r_src_class = r_src_class.strip(" \t\v\r\n")
        r_dst_class = src2dst.get(r_src_class.lower(), None)
        if isinstance(r_dst_class, str) is False:
            print("*"*100)
            print(f"unresolved class: {r_src_class.lower() }")
            break
        print(f"[{i_class}]: {r_src_class} => {r_dst_class}")


# print(f"num dst class: {len(set(src2dst.values()))}")
